---
format: 
  pdf:
    documentclass: report
    fontsize: 12pt
    mainfont: "Times New Roman"
    pagestyle: empty
    papersize: a4
    geometry: 
      - top=10mm
      - bottom=20mm
      - left=20mm
      - right=20mm
editor: source
---


```{r pendahuluan}
#| include: false
source("script/bast.R")
i <- 4
bast <- tbl_bast |> slice(i)
```


<!--
Bagian ini agar kata tidak terpotong. 
Prevent LaTeX from hyphenating the entire document
-->

\tolerance=1
\emergencystretch=\maxdimen
\hyphenpenalty=10000
\hbadness=10000

<!--
Document Begins
-->


\begin{center}

\strong{BERITA ACARA SERAH TERIMA HASIL PEKERJAAN}

\strong{PETUGAS PENGOLAHAN SURVEI DAN SENSUS}

\strong{TAHUN 2024}


Nomor: `r bast$bast.nomor`
\end{center}

\hfill \break <!-- nambah [ENTER] -->


Pada hari ini `r tbl_bast$bast.tanggal[i] |> as.character() |> terbilang_tanggal()`, bertempat di Maumere, kami yang bertanda tangan di bawah ini:

\begin{tabular}{p{4cm}p{0.5cm}l}
Nama                  & : & `r ppk.nama` \\
NIP                 & : & `r ppk.nip` \\
Jabatan             & : & `r ppk.jabatan` \\
Unit Kerja           & :  & `r ppk.unit_kerja`  \\
Alamat Unit Kerja      & : & `r ppk_unit_kerja_alamat`   \\
\end{tabular}


bertindak untuk dan atas nama BPS Kabupaten Sikka, selanjutnya disebut sebagai PIHAK PERTAMA.

\begin{tabular}{p{4cm}p{0.5cm}l}
Nama        & : & `r bast$mitra.nama` \\
NIK         & : & `r bast$mitra.nik` \\
Alamat      & : & `r bast$mitra.alamat |> str_to_upper()`   \\
\end{tabular}

bertindak untuk dan atas namanya sendiri, selanjutnya disebut sebagai PIHAK KEDUA.

Dengan ini menyatakan:  

1.	PIHAK KEDUA telah melaksanakan pekerjaan Pengolahan Survei dan Sensus berdasarkan Surat Perjanjian Kerja PENGOLAHAN SURVEI DAN SENSUS pada Badan Pusat Statistik Kabupaten Sikka Nomor: `r bast$spk.nomor`.

2.	PIHAK KEDUA telah menyelesaikan pekerjaan Pengolahan Survei dan Sensus berdasarkan hasil pemeriksaan dan evaluasi pekerjaan sebagaimana tercantum dalam lampiran. 

3.	Berdasarkan angka 2 tersebut di atas, PIHAK KEDUA menyerahkan hasil pekerjaan Pengolahan Survei dan Sensus kepada PIHAK PERTAMA, dan PIHAK PERTAMA menerima hasil pekerjaan tersebut yang telah sesuai dengan seharusnya;

4.	Hasil pekerjaan Pengolahan Survei dan Sensus sebagaimana dimaksud dalam angka 3 di atas, berupa dokumen yang sudah dientri sejumlah `r bast$goal_txt`.

Demikian Berita Acara ini dibuat dengan sebenarnya dalam rangkap 2 (dua) dan menjadi sah berlaku setelah ditandatangani oleh KEDUA BELAH PIHAK.

\hfill \break <!-- nambah [ENTER] -->

\begin{center}
\begin{tabular}{cp{5cm}c}
PIHAK PERTAMA & & PIHAK KEDUA \\
  &  &  \\
  &  &  \\
  &  &  \\
  &  &  \\
`r bast$mitra.nama`   & & `r ppk.nama`    \\
\end{tabular}
\end{center}
